move pytest, mypy, isort, autopep8, flake8, configs to setup.cfg
- delete pyproject.toml
- add setup.py to prevent error:
python3 -m pip install .
ERROR: Directory '.' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.
- .bumpversion.cfg config can be moved to setup.cfg, but in practice it converts it to mess on commit